// <auto-generated />
using CarRental.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRental.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRental.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Fuel")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Mileage")
                        .HasColumnType("INT");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Seats")
                        .HasColumnType("INT");

                    b.Property<int>("Year")
                        .HasColumnType("INT");

                    b.Property<string>("about")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("combisudan")
                        .HasColumnType("varchar(20)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
